Feature/fe 13
ACME-Delivery-Service/DeliverySystem_Frontend pull request #2
Opened 2018-10-24 19:29 UTC by AnastasiaVorton

Я смог

2018-10-24 19:43 UTC, arrilight requested changes

2018-10-24 19:43 UTC, arrilight commented on src/app/components/dumb/parcel-card/parcel-card.component.css
> +.ag_map {
naming style

2018-10-24 19:43 UTC, arrilight commented on src/app/components/dumb/parcel-card/parcel-card.component.html
> +        <td>Assigneg to</td>
assigned

2018-10-24 19:43 UTC, arrilight commented on src/app/components/dumb/parcel-card/parcel-card.component.ts
> +  // driver: OperatorInterface;
delete unused import or use default value

2018-10-24 19:43 UTC, arrilight commented on src/app/components/dumb/parcel-card/parcel-card.component.ts
> +  open(content) {
access modifier is missing

2018-10-24 19:43 UTC, arrilight commented on src/app/components/dumb/parcel-card/parcel-card.component.ts
> +  close() {
the same with the access modifier

2018-10-24 19:43 UTC, arrilight commented on src/app/components/dumb/parcel-card/parcel-card.component.ts
> +  ngOnInit() {}
should be after constructor

2018-10-24 19:43 UTC, arrilight commented on src/app/components/dumb/parcels-table/parcels-table.component.html
> +      <!--<td>{{ parcel.id }}</td>-->
is this really needed?

2018-10-24 19:43 UTC, arrilight commented on src/app/components/dumb/delivery-map/delivery-map.component.html
> +      <agm-map class="ag_map" [latitude]="lat" [longitude]="lng" [zoom]="15">
maybe better to move 15 to the component?

2018-10-24 19:45 UTC, arrilight commented on src/app/components/dumb/parcel-card/parcel-card.component.ts
> +  ngOnInit() {}
or should be here at all, it is empty ;D

2018-10-24 19:54 UTC, arrilight requested changes
.lock files shouldn't be in commit when you don't change package.json

2018-10-25 07:57 UTC, AnastasiaVorton commented on src/app/components/dumb/parcel-card/parcel-card.component.css
> +.ag_map {
Поправлю еще в Деливери мап, я оттуда брала))

2018-10-25 07:59 UTC, AnastasiaVorton commented on src/app/components/dumb/parcel-card/parcel-card.component.ts
> +  open(content) {
Хз что это)00

2018-10-25 07:59 UTC, AnastasiaVorton commented on src/app/components/dumb/parcel-card/parcel-card.component.ts
> +  close() {
same))

2018-10-25 08:24 UTC, arrilight commented on src/app/components/dumb/parcel-card/parcel-card.component.ts
> +  open(content) {
public/private –– все методы, кроме ngOnInit и т.д., по-хорошему, должны иметь модификатор доступа

2018-10-25 08:25 UTC, arrilight approved these changes

2018-10-25 08:25 UTC, merged